services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  fastapi:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - ./app/.env

  frontend_customer:
    build:
      context: ./frontend/frontend_user
      dockerfile: Dockerfile
      args:
        - no_cache=true
    container_name: frontend_customer
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/frontend_user:/app
      - /app/node_modules

  frontend_restaurant:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
      args:
        - no_cache=true
    container_name: frontend_restaurant
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules

volumes:
  mongo-data: